name: Test + Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Version in Leap/SLE 15
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install flake8
        sudo apt update
        sudo apt install -y podman
    - name: Lint
      run: make lint
    - name: Test
      run: make test
